### ISSUE TITLE
Questions about the whole accelerator

### ISSUE THREAD

**Issue by lloo099** [NetDBFPGA/ecv2021_demo#2]
Hi, thanks for your open-source sharing. But I have some confusion about this network. As you mentioned this accelerator is implemented based on ResNet18. However, it seems the VGG network is in your open source codes (ZCU102 demo). If you mind sharing this information? Secondly, the LK-OF algorithm can be deployed on smaller edge devices like Ultra96 if we use Mobilenet as an example. Hope for your feedback, thanks.

**Comment by JiaMingLin** [comment]
Hi,
Thanks for your interests. 
1. We implemented the accelerator by our self that time, and do encounter some implementation issues, so we only put the simplest version in this repository for demo action recognition based on FPGA. We are recently working to improve this part.
2. Yes, that is an interesting idea and also challenging, thanks a lot.

**Comment by lloo099** [comment]
> Hi, Thanks for your interests.
> 
> 1. We implemented the accelerator by our self that time, and do encounter some implementation issues, so we only put the simplest version in this repository for demo action recognition based on FPGA. We are recently working to improve this part.
> 2. Yes, that is an interesting idea and also challenging, thanks a lot.

Thanks for your quick response. Looking forwarding to your updates :)

**Comment by lloo099** [comment]
> Hi, Thanks for your interests.
> 
> 1. We implemented the accelerator by our self that time, and do encounter some implementation issues, so we only put the simplest version in this repository for demo action recognition based on FPGA. We are recently working to improve this part.
> 2. Yes, that is an interesting idea and also challenging, thanks a lot.

Sorry, I have one more question about your simplest version. Would you mind sharing your hardware resources utilization of this VGG version and also its performance?

**Comment by JiaMingLin** [comment]
The resource utilization is reported in the [paper](https://openaccess.thecvf.com/content/CVPR2021W/ECV/papers/Lin_Efficient_Two-Stream_Action_Recognition_on_FPGA_CVPRW_2021_paper.pdf), table 2.
And we did not report the latency, throughput and energy, since we were not very confident about using PYNQ to evaluate that time. But recently, there are more and more reports on top conferences using PYNQ, and also open sourced, e.g. CodeNet in FPGA 2021, which are good references.

**Comment by lloo099** [comment]
> The resource utilization is reported in the [paper](https://openaccess.thecvf.com/content/CVPR2021W/ECV/papers/Lin_Efficient_Two-Stream_Action_Recognition_on_FPGA_CVPRW_2021_paper.pdf), table 2. And we did not report the latency, throughput and energy, since we were not very confident about using PYNQ to evaluate that time. But recently, there are more and more reports on top conferences using PYNQ, and also open sourced, e.g. CodeNet in FPGA 2021, which are good references.

Noted with thanks!
